---
repository_rpmfusion_free_key:
  RedHat:
    "7":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-7"
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-8"
  CentOS:
    "7":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-7"
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-8"
  Rocky:
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-8"
  AlmaLinux:
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-8"
  Amazon:
    "2":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-7"
  Fedora:
    "33":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    "34":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    "35":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"

repository_rpmfusion_nonfree_key:
  RedHat:
    "7":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-7"
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-8"
  CentOS:
    "7":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-7"
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-8"
  Rocky:
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-8"
  AlmaLinux:
    "8":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-8"
  Amazon:
    "2":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-7"
  Fedora:
    "33":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
    "34":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
    "35":
      - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"


##################
# This part maps ansible_distribution to a generic value used by rpmfusion.
_rpmfusion_distribution:
  default: el
  Fedora: "{{ ansible_distribution | lower }}"

rpmfusion_distribution: "{{ _rpmfusion_distribution[ansible_distribution] | default(_rpmfusion_distribution['default'] ) }}"

# Amazon uses "2018" and "2", which are similar to respectively 6 and 7.
_rpmfusion_distribution_major_version:
  "2018": 6
  "2": 7

# Not all distributions (for example RedHat, CentOS and Fedora) need
# modifiction, therefor the default value is ansible_distribution_major_version.
rpmfusion_distribution_major_version: "{{ _rpmfusion_distribution_major_version[ansible_distribution_major_version] | default(ansible_distribution_major_version) }}"

# The URL to the gpg key differs, so we need to map distribution to the
# identifier that rpmfusion uses.
_rpmfusion_gpgkey:
  default: "{{ rpmfusion_distribution_major_version }}"
  Fedora: 2020

rpmfusion_gpgkey: "{{ _rpmfusion_gpgkey[ansible_distribution] | default(_rpmfusion_gpgkey['default'] ) }}"

rpmfusion_free_repository: "https://download1.rpmfusion.org/free/{{ rpmfusion_distribution }}/rpmfusion-free-release-{{ rpmfusion_distribution_major_version }}.noarch.rpm"
rpmfusion_nonfree_repository: "https://download1.rpmfusion.org/nonfree/{{ rpmfusion_distribution }}/rpmfusion-nonfree-release-{{ rpmfusion_distribution_major_version }}.noarch.rpm"

rpmfusion_free_gpgp_key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-{{ rpmfusion_distribution }}-{{ rpmfusion_gpgkey }}"
rpmfusion_nonfree_gpgp_key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-{{ rpmfusion_distribution }}-{{ rpmfusion_gpgkey }}"
