---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    molecule_repo_file_free: "rpmfusion-free-updates.repo"
    molecule_repo_file_nonfree: "rpmfusion-nonfree-updates.repo"
    molecule_repo_name_free: "rpmfusion-free-updates"
    molecule_repo_name_nonfree: "rpmfusion-nonfree-updates"
    molecule_repo_package_free: "x264-libs"

    molecule_repo_package_nonfree_map:
      RedHat:
        "7":
          - "pgplot"
        "8":
          - "pgplot"
        "9":
          - "xrick"
      CentOS:
        "7":
          - "pgplot"
        "8":
          - "pgplot"
        "9":
          - "xrick"
      Amazon: "pgplot"
      Fedora: "pgplot"
      default: "pgplot"

      molecule_repo_package_nonfree: "{{ molecule_repo_package_nonfree_map[ansible_distribution][ansible_distribution_major_version] | molecule_repo_package_nonfree_map[ansible_distribution] | default(molecule_repo_package_nonfree_map['default']) }}"

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: "Test if repository exists and is enabled (free)"
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ molecule_repo_file_free }}"
        section: "{{ molecule_repo_name_free }}"
        option: enabled
        value: "1"
        no_extra_spaces: true
        mode: "0644"
      register: molecule_repository_free
      failed_when: (molecule_repository_free is changed) or (molecule_repository_free is failed)

    - name: Check package is installable from repository (free)
      ansible.builtin.yum:
        name: "{{ molecule_repo_package_free }}"
        state: present

    - name: Test if repository exists and is enabled (nonfree)
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ molecule_repo_file_nonfree }}"
        section: "{{ molecule_repo_name_nonfree }}"
        option: enabled
        value: "1"
        no_extra_spaces: true
        mode: "0644"
      register: molecule_repository_nonfree
      failed_when: (molecule_repository_nonfree is changed) or (molecule_repository_nonfree is failed)

    - name: Check package is installable from repository (nonfree)
      ansible.builtin.yum:
        name: "{{ molecule_repo_package_nonfree }}"
        state: present
